### ISSUE TITLE
Compiling issue [Windows] : error C2039 '...' not member of std

### ISSUE THREAD

**Issue by Arag24** [ifm/ifm3d-examples#13]
I compiled ifm3d 0.15.1 succesfully and started a new clone of ifm3d-example.

However, I can not make it.
Both ex-multi_camera_grabber and ex-timestamp project are not compiling due to some C2039 / C3861 errors.

`error C2039: 'time_t': is not a member of 'std'`

Thinking it was an old version of my VS Studio, I updated it. No change.

My environment is following :
```
-- The CXX compiler identification is MSVC 19.16.27032.1 (Visual Studio 2017 version 15.9.15)
-- Windows SDK version 10.0.17763.0

```
Any ideas ? I will go deeper, too, from my side...

**Comment by theseankelly** [comment]
`time_t` is part of the `<ctime>` header (https://en.cppreference.com/w/cpp/chrono/c/time_t) and this header is not included by either project you mention. Perhaps it gets included in some system library on Linux and not on Windows. Either way it should be explicitly included. If you want to try it and submit a PR I'll happily push it through, assuming that solves your issues. Otherwise give me a day or two and I'll to get to it.
